import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { UserPovider } from "@/contexts/UserContext";
import BottomNav from "@/components/ButtomNav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased bg-white`}
    >
      <UserPovider>
        <body>
          <Header />
          <BottomNav />
          <main className="bg-white">
            {children}
          </main>
        </body>
      </UserPovider>
    </html>
  );
}
